# Generated by Django 5.2.8 on 2025-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='cod_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
    ]
